#!/bin/bash
export ACCESS_CRED='AKIAIZX76FSWZCJPHGXQ'
export SECRET_CRED='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'
export S3_BUCKET='siggame-gamelogs'
export CLIENT_PREFIX='ssh://mnuck@r99acm.device.mst.edu:2222/home/mnuck/clients'

cd /home/gladiator/arena

# gather up the fixed components
scp mies@mnuck.com:/home/mies/arena/referee.py .
scp mies@mnuck.com:/home/mies/arena/blaster.py .
scp mies@mnuck.com:/home/mies/mysite/mysite/thunderdome/models.py \
            /home/gladiator/djangolol/thunderdome/models.py
git clone ssh://mies@mnuck.com/home/mies/arena/server

# open ssh tunnels. 5432 is postgresql, 11300 is beanstalkd
ssh -f -N \
    -L 5432:mnuck.com:5432 \
    -L 11300:mnuck.com:11300 \
    mies@mnuck.com
	    
./blaster.py
	    
exit 0
